server:
  port: ${PORT:5000}

base-url: /api

spring:
  application:
    name: taskManager

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none
